name: Run nvcc compile containing cudnn.h

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        channels: conda-forge
        auto-update-conda: true
        python-version: 3.12.7

    - name: Run command
      run: |
        conda install -c conda-forge -y cuda-toolkit cudnn
        nvcc test.cu -o test
